import { getRandomArbitrary } from '../prototypes/prototype_1/utilities'

document.addEventListener('DOMContentLoaded', () => {
  console.log('Test ', getRandomArbitrary(0, 1))

  const container = document.getElementById('prototype_3')
  const framebox = document.createElement('div')
  const frame = document.createElement('div')
  const frame2 = document.createElement('div')
  const frame3 = document.createElement('div')
  const frame4 = document.createElement('div')
  const frame5 = document.createElement('div')
  const frame6 = document.createElement('div')
  const frame7 = document.createElement('div')
  const frame8 = document.createElement('div')
  const frame9 = document.createElement('div')
  const man = document.createElement('div')
  const manbody = document.createElement('div')
  const ear = document.createElement('div')
  const ear2 = document.createElement('div')
  const eye = document.createElement('div')
  const eye2 = document.createElement('div')
  const mouth = document.createElement('div')
  const teeth = document.createElement('div')
  const teeth2 = document.createElement('div')
  const text = document.createElement('p')
  text.innerText = 'Who am I?'

  framebox.classList.add('framebox')
  frame.classList.add('frame')
  frame2.classList.add('frame')
  frame3.classList.add('frame')
  frame4.classList.add('frame')
  frame5.classList.add('frame')
  frame6.classList.add('frame')
  frame7.classList.add('frame')
  frame8.classList.add('frame')
  frame9.classList.add('frame')
  man.classList.add('man')
  manbody.classList.add('manbody')
  ear.classList.add('ear')
  ear2.classList.add('ear')
  ear2.classList.add('ear2')
  eye.classList.add('eye')
  eye2.classList.add('eye')
  eye2.classList.add('eye2')
  mouth.classList.add('mouth')
  teeth.classList.add('teeth')
  teeth2.classList.add('teeth')
  teeth2.classList.add('teeth2')

  container.appendChild(framebox)
  framebox.appendChild(frame)
  framebox.appendChild(frame2)
  framebox.appendChild(frame3)
  framebox.appendChild(frame4)
  framebox.appendChild(frame5)
  framebox.appendChild(frame6)
  framebox.appendChild(frame7)
  framebox.appendChild(frame8)
  framebox.appendChild(frame9)
  container.appendChild(man)
  man.appendChild(manbody)
  man.appendChild(ear)
  man.appendChild(ear2)
  man.appendChild(eye)
  man.appendChild(eye2)
  man.appendChild(mouth)
  mouth.appendChild(teeth)
  mouth.appendChild(teeth2)
  frame9.appendChild(text)



})
